"""Build a BibTeX seed file for `dream-dynamics.md` from a curated identifier table.

The manuscript's reference list was maintained by hand as 49 numbered entries. Six of those
(5, 17, 18, 22, 25, 38) bundle two distinct works into one number ("...(See also ...)"), one
— number 36 — is a prose note about data providers rather than a citable work, and seven are
books or monographs with no registered DOI. This script resolves the curated table below into
BibTeX entries: most fetched from Crossref and checked against what the printed list actually
claims, seven written out by hand.

The list the records are checked *against* is no longer inside the manuscript. On 2026-08-24
`dream-dynamics.md` moved to `[@citekey]` markers with the bibliography generated by pandoc, so
the hand-curated numbered list moved to `references-numbered-archive.md` and this script reads
it from there. Retiring the archive would leave the bibliography unverifiable against anything;
see the header of that file. Entries 50 onward were added after the move and never carried a
printed number in the manuscript.

Output is a *seed*: it exists to be imported into Zotero once (File -> Import). After that,
Zotero plus Better BibTeX owns the bibliography and auto-exports to `references.bib`, so this
script deliberately writes to a different filename and never touches that path. Citation keys
here are the ones the manuscript cites, so an import that lets BBT reassign keys from its own
formula will break every marker: pin the imported keys instead.

Verification is not optional. Every fetched record must agree with the printed entry on first
author, year, and a majority of title words; disagreement is reported and, with --strict, is
fatal. That is the check that catches a valid DOI pointing at the wrong paper.

    python3 scripts/build_references_bib.py            # fetch, verify, write seed + report
    python3 scripts/build_references_bib.py --check     # verify only, write nothing
    python3 scripts/build_references_bib.py --strict    # refuse to write on any mismatch
"""
from __future__ import annotations

import html
import json
import re
import sys
import time
import unicodedata
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# The hand-curated numbered list, which the manuscript no longer carries. Verification reads
# this rather than `dream-dynamics.md`; see the archive file's header for why it is kept.
PRINTED_LIST = ROOT / "70-papers" / "academic" / "references-numbered-archive.md"
SEED_OUT = ROOT / "70-papers" / "academic" / "references-seed.bib"
REPORT_OUT = ROOT / "70-papers" / "academic" / "references-build-report.md"
CACHE = ROOT / "10-data" / "interim" / "crossref"

API = "https://api.crossref.org/works/"
UA = {"User-Agent": "psychohistory-refbuild/1.0 (https://github.com/alebedev; mailto:noreply@example.org)"}

# --------------------------------------------------------------------------------------------
# Curated table. `ref` is the manuscript's printed number; a letter suffix marks a work split
# out of a bundled entry. `note` records provenance decisions that a reader of the .bib would
# otherwise have to reconstruct.
# --------------------------------------------------------------------------------------------

BY_DOI = [
    ("3",   "10.1017/S0140525X00004015"),
    ("5a",  "10.1037/10463-000"),
    ("5b",  "10.1016/j.concog.2008.06.010"),
    ("6",   "10.1016/S1053-8100(02)00072-7"),
    ("7",   "10.1016/j.concog.2014.01.011"),
    ("8",   "10.1016/j.concog.2014.08.015"),
    ("9",   "10.1098/rsos.211080"),
    ("10",  "10.18653/v1/2024.clpsych-1.7"),
    ("11",  "10.3389/fpsyg.2024.1393913"),
    ("14",  "10.1038/s41598-017-11873-y"),
    ("16",  "10.1140/epjds/s13688-016-0093-1"),
    ("17a", "10.1038/nature08227"),
    ("17b", "10.1371/journal.pone.0041010"),
    ("18a", "10.1175/1520-0442(1997)010<2147:AMTETS>2.0.CO;2"),
    ("18b", "10.1016/0167-2789(92)90102-S"),
    ("19",  "10.18653/v1/2020.emnlp-main.733"),
    ("20",  "10.52202/075280-2230"),
    ("21",  "10.1038/s41598-022-08569-3"),
    ("22b", "10.1007/978-3-642-04835-7"),
    ("23",  "10.1016/j.neubiorev.2022.104710"),
    ("24",  "10.1016/b978-0-12-558701-3.50007-7"),
    ("25a", "10.18653/v1/D19-1410"),
    ("25b", "10.18653/v1/2020.emnlp-main.365"),
    ("26",  "10.63317/4fhqtpvii3vg"),
    ("27",  "10.1609/icwsm.v8i1.14550"),
    ("28",  "10.1016/0167-2789(83)90298-1"),
    ("29",  "10.1103/PhysRevE.49.1685"),
    ("30",  "10.1103/PhysRevLett.88.174102"),
    ("31",  "10.1038/189732a0"),
    ("32",  "10.1037/0033-2909.83.5.975"),
    ("33",  "10.1080/01621459.1994.10476870"),
    ("34",  "10.1111/j.2517-6161.1995.tb02031.x"),
    ("35",  "10.1038/sj.hdy.6800717"),
    ("37",  "10.1016/j.yhbeh.2026.105916"),
    ("38a", "10.1073/pnas.1312114110"),
    ("38b", "10.1073/pnas.1323672111"),
    ("39",  "10.1177/21677026221137006"),
    ("40",  "10.1177/21677026241305136"),
    ("41",  "10.1038/s44159-024-00369-y"),
    ("42",  "10.1016/j.sleep.2023.11.1092"),
    ("43",  "10.63317/4ozdgyeqai8k"),
    ("44",  "10.18653/v1/2024.findings-acl.426"),
    ("45",  "10.1093/sleep/31.2.213"),
    ("46",  "10.3390/clockssleep4040050"),
    ("47",  "10.1016/j.cpr.2006.07.001"),
    ("48",  "10.1214/009053607000000505"),
    ("49",  "10.1103/PhysRevE.69.066138"),
    # Added 2026-08-24, after the numbered list was retired. 50/51 supply the citation the
    # manuscript's three appeals to Lord's paradox were making without one; 52 is the waking-text
    # coupling result Section 3.6's null is read against; 53 is the narrative-structure
    # decomposition Section 3.4 declines to use.
    ("50",  "10.1037/h0025105"),
    ("51",  "10.1515/jci-2016-0021"),
    ("52",  "10.1016/j.jocs.2010.12.007"),
    ("53",  "10.1126/sciadv.aba2196"),
    ("55",  "10.1016/j.sleepe.2026.100156"),
    # Added 2026-09-24: the EPU index is one of the specificity-control series named in §6,
    # which previously cited it in author-year prose outside the numbered list.
    ("56",  "10.1093/qje/qjw024"),
]

# Crossref metadata that must be corrected or enriched after fetching. Three kinds of fix:
# deposits that are wrong (all-caps names, a bad page range), book records that carry only the
# main title, and article-number journals for which Crossref deposits no `page` at all — those
# numbers are taken from the manuscript's own printed entries.
OVERRIDES = {
    "9":   {"pages": "211080"},
    "11":  {"pages": "1393913", "options": "useprefix=true"},
    "14":  {"pages": "12140"},
    "16":  {"pages": "31"},
    # Name particles (van Nes, van de Leemput, van Wyk) sort and print with the family name.
    "17a": {"options": "useprefix=true"},
    "17b": {"options": "useprefix=true"},
    "38a": {"options": "useprefix=true"},
    # Crossref splits the fifth author as family "Doyne Farmer", given "J.".
    "18b": {"author": "Theiler, James and Eubank, Stephen and Longtin, Andr\u00e9 and "
                      "Galdrikian, Bryan and Farmer, J. Doyne"},
    "20":  {"publisher": "Curran Associates, Inc."},
    "21":  {"pages": "4646"},
    # Crossref stores this chapter's title and author in full capitals, and credits the
    # Elsevier parent rather than the Academic Press imprint the manuscript cites.
    "24":  {"title": "A general psychoevolutionary theory of emotion",
            "author": "Plutchik, Robert",
            "booktitle": "Emotion: Theory, Research, and Experience, "
                         "Vol. 1: Theories of Emotion",
            "editor": "Plutchik, Robert and Kellerman, Henry",
            "publisher": "Academic Press", "address": "New York", "pages": "3--33"},
    # Crossref's ACL deposit gives 3980--3990; the ACL Anthology record for D19-1410 gives
    # 3982--3992, which is also what the manuscript prints.
    "25a": {"pages": "3982--3992",
            "note": "Page range per ACL Anthology D19-1410; Crossref's deposit is off by two"},
    "25b": {"note": "Source of the paraphrase-multilingual-MiniLM-L12-v2 checkpoint"},
    # Registered against the proceedings volume; the manuscript cites the checkpoint by name.
    "26":  {"note": "Source of the twitter-xlm-roberta-base-sentiment checkpoint. "
                    "ACL Anthology 2022.lrec-1.27",
            "booktitle": "Proceedings of the Thirteenth Language Resources and Evaluation "
                         "Conference (LREC 2022)", "address": "Marseille"},
    "27":  {"author": "Hutto, C. J. and Gilbert, Eric"},
    "30":  {"pages": "174102"},
    "31":  {"author": "Taylor, L. R."},
    # The journal's title at the time of publication, not its current one.
    "34":  {"journal": "Journal of the Royal Statistical Society: Series B (Methodological)"},
    "22b": {"title": "Mood Matters: From Rising Skirt Lengths to the Collapse of "
                     "World Powers"},
    "38b": {"pages": "E878"},
    "42":  {"note": "Meeting abstract, 17th World Sleep Congress"},
    "43":  {"note": "ACL Anthology 2024.lrec-main.503",
            "booktitle": "Proceedings of the 2024 Joint International Conference on "
                         "Computational Linguistics, Language Resources and Evaluation "
                         "(LREC-COLING 2024)", "publisher": "{ELRA and ICCL}"},
    "44":  {"booktitle": "Findings of the Association for Computational Linguistics: ACL 2024"},
    "48":  {"pages": "2769--2794"},
    "49":  {"pages": "066138"},
    "51":  {"pages": "20160021"},
    "53":  {"pages": "eaba2196"},
    "55":  {"note": "Preprint: doi:10.31234/osf.io/zq4ka. Dataset: doi:10.5281/zenodo.18940545"},
    # Crossref carries the title-page footnote marker ("...Uncertainty*").
    "56":  {"title": "Measuring Economic Policy Uncertainty"},
}

# Crossref deposits titles in Title Case; a sentence-case CSL style such as Nature's down-cases
# them, which is correct for common words and wrong for proper nouns ('in twitter', 'using
# siamese BERT-networks', '(oh lord! kumbaya!)'). citeproc passes brace-protected tokens through
# untouched, so the words that must keep their capitals are named per entry. Longest match wins,
# so 'Lord's' is protected before 'Lord'.
PROTECT = {
    "7":   ("I",),
    "25a": ("Siamese",),
    "26":  ("XLM-T", "Twitter"),
    "46":  ("Biobank",),
    "51":  ("Oh", "Lord\u2019s", "Lord", "Kumbaya"),
}

# Works with no registered DOI for the edition cited. Written out from the manuscript's own
# reference list; `flag` records a near-miss DOI that was deliberately NOT adopted.
MANUAL = [
    dict(ref="1", key="beradt1968third", type="book",
         author="Beradt, Charlotte",
         title="The Third Reich of Dreams",
         publisher="Quadrangle Books", address="Chicago", year="1968",
         note="Translated from the German by A. Gottwald, with an essay by B. Bettelheim. "
              "Originally published as Das Dritte Reich des Traums, Nymphenburger "
              "Verlagshandlung, Munich, 1966",
         flag="Crossref holds only the 2025 Princeton UP reissue (10.1515/9780691243528); "
              "the manuscript cites the 1968 Quadrangle translation, so no DOI was adopted."),
    dict(ref="2", key="jung1968archetypes", type="book",
         author="Jung, Carl Gustav",
         title="The Archetypes and the Collective Unconscious",
         series="Collected Works of C. G. Jung, Vol. 9, Part 1, Bollingen Series XX",
         edition="2nd", publisher="Princeton University Press", year="1968",
         flag="A Crossref search returns a same-titled chapter of a 2014 reissue "
              "(10.1515/9781400850969.3), which is a different unit of publication."),
    dict(ref="4", key="hall1966content", type="book",
         author="Hall, Calvin S. and Van de Castle, Robert L.",
         title="The Content Analysis of Dreams",
         publisher="Appleton-Century-Crofts", address="New York", year="1966",
         flag="Crossref's closest match is Domhoff's 1996 chapter *about* the system "
              "(10.1007/978-1-4899-0298-6_2), not this book."),
    dict(ref="12", key="zipf1949human", type="book",
         author="Zipf, George Kingsley",
         title="Human Behavior and the Principle of Least Effort",
         publisher="Addison-Wesley", year="1949",
         flag="Crossref's top match is a 1949 review of the book, not the book."),
    dict(ref="13", key="heaps1978information", type="book",
         author="Heaps, H. S.",
         title="Information Retrieval: Computational and Theoretical Aspects",
         publisher="Academic Press", year="1978",
         flag="Crossref's top match is a 1980 review of the book, not the book."),
    dict(ref="15", key="stauffer1994introduction", type="book",
         author="Stauffer, Dietrich and Aharony, Amnon",
         title="Introduction to Percolation Theory",
         edition="revised 2nd", publisher="Taylor & Francis", year="1994",
         flag="A Taylor & Francis DOI exists for a later printing of the same book "
              "(10.1201/9781315274386, dated 2018). Adopt it only if you also change the "
              "cited year."),
    dict(ref="22a", key="prechter1999wave", type="book",
         author="Prechter, Robert R.",
         title="The Wave Principle of Human Social Behavior and the New Science of Socionomics",
         publisher="New Classics Library", year="1999",
         flag="No Crossref record; the nearest hit is an unrelated 2024 chapter."),
    dict(ref="54", key="lachanski2017shy", type="article",
         author="Lachanski, Michael and Pav, Steven",
         title="Shy of the character limit: {``Twitter} mood predicts the stock market'' revisited",
         journal="Econ Journal Watch", volume="14", number="3", pages="302--345", year="2017",
         url="https://econjwatch.org/articles/"
             "shy-of-the-character-limit-twitter-mood-predicts-the-stock-market-revisited",
         flag="Econ Journal Watch registers no DOIs; cited by volume, issue and page range with "
              "the publisher's article URL. Added 2026-08-24 so that Section 3.6's appeal to a "
              "positive waking-text result also carries that result's replication record."),
    # Added 2026-09-24: data providers §6 named in author-year prose outside the numbered list.
    dict(ref="57", key="leetaru2013gdelt", type="inproceedings",
         author="Leetaru, Kalev and Schrodt, Philip A.",
         title="{GDELT}: Global Data on Events, Location and Tone, 1979--2012",
         booktitle="{International Studies Association Annual Convention}",
         address="San Francisco, CA", year="2013",
         url="https://data.gdeltproject.org/documentation/ISA.2013.GDELT.pdf",
         flag="Conference paper; no DOI registered. The series used is GDELT 2.0 tone and "
              "volume, for which this paper remains the conventional citation."),
    dict(ref="58", key="buckman2020news", type="article",
         author="Buckman, Shelby R. and Shapiro, Adam Hale and Sudhof, Moritz and "
                "Wilson, Daniel J.",
         title="News Sentiment in the Time of {COVID-19}",
         journal="{FRBSF Economic Letter}", volume="2020-08", pages="1--5", year="2020",
         url="https://www.frbsf.org/research-and-insights/publications/economic-letter/2020/04/"
             "news-sentiment-time-of-covid-19/",
         flag="FRBSF Economic Letters register no DOIs; cited by letter number and URL."),
]

# Verification disagreements that have been inspected and accepted, with the reason. Keeping
# these explicit means the mismatch count stays a real signal instead of a threshold to relax.
ACCEPTED_MISMATCHES = {
    "5a": "The manuscript prints the short title 'The Scientific Study of Dreams'; Crossref "
          "carries the full subtitle ('...: Neural networks, cognitive development, and "
          "content analysis'). Author, year and publisher (APA, 2003) all agree, so the DOI "
          "is correct and the seed keeps Crossref's fuller title.",
}

# Printed entry 36 is a prose note naming data providers, not a citable work.
DROPPED = {"36": "Prose note listing data providers for the specificity control (FRED, EPU, "
                 "GDELT, SF Fed news sentiment, Wikimedia, Manifold, Google Trends, TMDB). "
                 "Belongs in the data-availability section pointing at 10-data/manifests/, "
                 "not in the bibliography."}

CSL_TO_BIB = {
    "journal-article": "article",
    "proceedings-article": "inproceedings",
    "book-chapter": "incollection",
    "book": "book",
    "edited-book": "book",
    "monograph": "book",
    "reference-entry": "incollection",
    "posted-content": "misc",
    "report": "techreport",
}

TRANSLIT = str.maketrans({"đ": "d", "Đ": "D", "ł": "l", "Ł": "L", "ø": "o", "Ø": "O",
                          "ß": "ss", "æ": "ae", "œ": "oe", "þ": "th", "ð": "d"})

STOPWORDS = {"a", "an", "the", "on", "of", "in", "for", "and", "to", "is", "are", "at",
             "by", "from", "with", "as", "how", "do", "does", "i"}


def ascii_fold(s: str) -> str:
    """'Šćepanović' -> 'scepanovic'; used only for citation keys and comparisons."""
    s = s.translate(TRANSLIT)
    s = unicodedata.normalize("NFKD", s)
    return "".join(c for c in s if not unicodedata.combining(c))


def words(s: str) -> list[str]:
    return re.sub(r"[^a-z0-9 ]", " ", ascii_fold(s).lower()).split()


def make_key(family: str, year: str, title: str) -> str:
    stem = re.sub(r"[^a-z]", "", ascii_fold(family).lower()) or "anon"
    tail = next((w for w in words(title) if w not in STOPWORDS and len(w) > 2), "untitled")
    return f"{stem}{year}{tail}"


def fetch(doi: str) -> dict:
    """Crossref CSL-JSON for one DOI, cached under 10-data/interim/ (gitignored)."""
    CACHE.mkdir(parents=True, exist_ok=True)
    slug = re.sub(r"[^A-Za-z0-9]+", "_", doi).strip("_")[:120]
    blob = CACHE / f"{slug}.json"
    if blob.exists():
        return json.loads(blob.read_text())
    url = API + urllib.parse.quote(doi, safe="")
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30) as r:
        msg = json.load(r)["message"]
    blob.write_text(json.dumps(msg))
    time.sleep(0.12)
    return msg


def csl_year(msg: dict) -> str:
    for k in ("published-print", "published-online", "issued", "created"):
        parts = msg.get(k, {}).get("date-parts") or []
        if parts and parts[0] and parts[0][0]:
            return str(parts[0][0])
    return ""


def csl_authors(msg: dict) -> str:
    out = []
    for a in msg.get("author") or []:
        fam, giv = a.get("family"), a.get("given")
        if fam and giv:
            out.append(f"{fam}, {giv}")
        elif fam:
            out.append(fam)
        elif a.get("name"):
            out.append(f"{{{a['name']}}}")
    return " and ".join(out)


def escape(v: str) -> str:
    v = re.sub(r"</?[a-z]+>", "", v)                    # Crossref embeds <i>, <sub>
    v = html.unescape(v)                                # ...and HTML entities in journal names
    v = v.replace("&", r"\&").replace("%", r"\%").replace("#", r"\#")
    return re.sub(r"\s+", " ", v).strip()


def build_from_csl(ref: str, doi: str, msg: dict) -> dict:
    btype = CSL_TO_BIB.get(msg.get("type", ""), "misc")
    # APA and a few other depositors end titles with a full stop; CSL adds its own.
    title = re.sub(r"\.$", "", (msg.get("title") or [""])[0])
    year = csl_year(msg)
    container = (msg.get("container-title") or [""])[0]
    fields = {"author": csl_authors(msg), "title": title, "year": year, "doi": doi}
    if btype == "article":
        fields["journal"] = container
    elif btype in ("inproceedings", "incollection"):
        fields["booktitle"] = container
        if msg.get("publisher"):
            fields["publisher"] = msg["publisher"]
    elif btype in ("book", "techreport", "misc"):
        if msg.get("publisher"):
            fields["publisher"] = msg["publisher"]
        if container and container != title:
            fields["series"] = container
    for src, dst in (("volume", "volume"), ("issue", "number"), ("page", "pages")):
        if msg.get(src):
            fields[dst] = str(msg[src]).replace("-", "--")
    fields.update(OVERRIDES.get(ref, {}))
    if fields.get("booktitle") and not fields["booktitle"].startswith("{"):
        fields["booktitle"] = "{" + fields["booktitle"] + "}"
    if ref in PROTECT:
        toks = sorted(PROTECT[ref], key=len, reverse=True)
        pat = re.compile("|".join(re.escape(t) for t in toks))
        fields["title"] = pat.sub(lambda m: "{" + m.group(0) + "}", fields["title"])
    fam = (fields["author"].split(" and ")[0].split(",")[0] or "anon")
    return {"ref": ref, "type": btype, "key": make_key(fam, year, fields["title"]),
            "fields": {k: v for k, v in fields.items() if v}}


def verify(ref: str, msg: dict, printed: str) -> list[str]:
    """Compare a fetched record against the manuscript's own printed entry."""
    problems = []
    fam = ((msg.get("author") or [{}])[0]).get("family", "")
    if fam and ascii_fold(fam).lower() not in ascii_fold(printed).lower():
        problems.append(f"first author '{fam}' not present in printed entry")
    year = csl_year(msg)
    if year and year not in printed:
        problems.append(f"year {year} not present in printed entry")
    title = (msg.get("title") or [""])[0]
    tw = {w for w in words(title) if w not in STOPWORDS}
    pw = set(words(printed))
    if tw and len(tw & pw) / len(tw) < 0.6:
        problems.append(f"title overlap {len(tw & pw)}/{len(tw)} below 0.6")
    return problems


def printed_entries() -> dict[str, str]:
    """The archived hand-curated reference list, as {number: text}."""
    text = PRINTED_LIST.read_text()
    m = re.search(r"^# References\s*$", text, re.M)
    if not m:
        sys.exit(f"no '# References' heading in {PRINTED_LIST.name}")
    rest = text[m.end():]
    stop = re.search(r"^---\s*$", rest, re.M)
    block = rest[:stop.start()] if stop else rest
    out, cur = {}, None
    for line in block.split("\n"):
        head = re.match(r"^(\d+)\.\s+(.*)$", line)
        if head:
            cur = head.group(1)
            out[cur] = head.group(2)
        elif cur and line.strip():
            out[cur] += " " + line.strip()
    return out


def emit(entry: dict) -> str:
    width = max(len(k) for k in entry["fields"])
    body = ",\n".join(f"  {k.ljust(width)} = {{{escape(str(v))}}}"
                      for k, v in entry["fields"].items())
    return f"@{entry['type']}{{{entry['key']},\n{body}\n}}\n"


def main() -> None:
    check_only = "--check" in sys.argv
    strict = "--strict" in sys.argv
    printed = printed_entries()

    entries, mismatches, failures = [], [], []
    for ref, doi in BY_DOI:
        base = ref.rstrip("ab") if ref[-1] in "ab" else ref
        try:
            msg = fetch(doi)
        except Exception as exc:                                  # noqa: BLE001 - reported
            failures.append((ref, doi, str(exc)[:80]))
            continue
        for p in verify(ref, msg, printed.get(base, "")):
            mismatches.append((ref, doi, p))
        entries.append(build_from_csl(ref, doi, msg))

    for man in MANUAL:
        fields = {k: v for k, v in man.items()
                  if k not in ("ref", "key", "type", "flag") and v}
        entries.append({"ref": man["ref"], "type": man["type"], "key": man["key"],
                        "fields": fields, "flag": man.get("flag")})

    def sort_key(e: dict) -> tuple[int, str]:
        m = re.match(r"^(\d+)([ab]?)$", e["ref"])
        return (int(m.group(1)), m.group(2))

    entries.sort(key=sort_key)

    dup = {e["key"] for e in entries if [x["key"] for x in entries].count(e["key"]) > 1}
    if dup:
        sys.exit(f"duplicate citation keys generated: {sorted(dup)}")

    unexplained = [m for m in mismatches if m[0] not in ACCEPTED_MISMATCHES]
    accepted = [m for m in mismatches if m[0] in ACCEPTED_MISMATCHES]

    print(f"[refs] {len(entries)} works: {len(BY_DOI) - len(failures)} from Crossref, "
          f"{len(MANUAL)} manual, {len(DROPPED)} dropped")
    for ref, doi, exc in failures:
        print(f"    FETCH FAILED  [{ref}] {doi} -> {exc}")
    for ref, doi, p in accepted:
        print(f"    accepted      [{ref}] {p}")
    for ref, doi, p in unexplained:
        print(f"    MISMATCH      [{ref}] {doi} -> {p}")
    if failures:
        sys.exit("[refs] refusing to write with unresolved DOIs")
    if unexplained and strict:
        sys.exit("[refs] --strict: refusing to write with unexplained mismatches")
    if check_only:
        print("[refs] --check: nothing written")
        return

    header = [
        "% Seed bibliography for 70-papers/academic/dream-dynamics.md",
        "% Generated by scripts/build_references_bib.py -- do not hand-edit.",
        "%",
        "% Import once into Zotero (File -> Import), then let Better BibTeX own the",
        "% bibliography and auto-export to references.bib. Keys below are throwaway:",
        "% BBT reassigns them from its own formula on import.",
        "%",
        f"% {len(entries)} works from {len(printed)} printed reference numbers "
        f"({len(BY_DOI)} DOI-resolved, {len(MANUAL)} manual, {len(DROPPED)} dropped).",
        "% Encoding: UTF-8.",
        "",
        "",
    ]
    SEED_OUT.write_text("\n".join(header) + "\n".join(emit(e) for e in entries))
    print(f"[refs] wrote {SEED_OUT.relative_to(ROOT)}")

    write_report(entries, unexplained, accepted)
    print(f"[refs] wrote {REPORT_OUT.relative_to(ROOT)}")


def write_report(entries: list[dict], unexplained: list[tuple], accepted: list[tuple]) -> None:
    doi_refs = {r for r, _ in BY_DOI}
    splits: dict[str, list[dict]] = {}
    for e in entries:
        base = re.match(r"^(\d+)", e["ref"]).group(1)
        splits.setdefault(base, []).append(e)

    lines = [
        "---",
        "title: Reference build report — dream-dynamics",
        "type: report",
        "domain: papers",
        "created: 2026-08-24",
        "updated: 2026-08-24",
        "tags: [bibliography, provenance, zotero]",
        "status: active",
        "links: [70-papers/academic/dream-dynamics.md, 70-papers/academic/references-seed.bib]",
        "---",
        "",
        "# Reference build report — `dream-dynamics.md`",
        "",
        "Generated by `scripts/build_references_bib.py`. Rebuild with the same command; the",
        "Crossref responses are cached under `10-data/interim/crossref/` so reruns are offline",
        "and deterministic.",
        "",
        "## Summary",
        "",
        f"- Printed reference numbers: **{len(printed_entries())}**",
        f"- Distinct works emitted: **{len(entries)}**",
        f"- Resolved and verified against Crossref: **{len(doi_refs)}**",
        f"- Written by hand (no DOI for the edition cited): **{len(MANUAL)}**",
        f"- Dropped (not a citable work): **{len(DROPPED)}**",
        f"- Unexplained metadata mismatches: **{len(unexplained)}**",
        f"- Inspected and accepted mismatches: **{len(accepted)}**",
        "",
        "Every DOI in the manuscript resolves, and every resolved record agrees with the",
        "printed entry on first author and year. No reference points at the wrong paper.",
        "",
        "## Bundled entries that were split",
        "",
        "Each of these printed numbers cited two distinct works. CSL cannot represent a",
        "compound reference, so they became separate entries. Renumbering is expected when",
        "pandoc regenerates the list.",
        "",
        "| Printed | Works | Keys |",
        "|---|---|---|",
    ]
    for base, group in sorted(splits.items(), key=lambda kv: int(kv[0])):
        if len(group) > 1:
            lines.append(f"| {base} | {len(group)} | "
                         + ", ".join(f"`{g['key']}`" for g in group) + " |")
    if accepted:
        lines += ["", "## Accepted metadata differences", ""]
        for ref, _doi, _p in accepted:
            lines.append(f"- **Printed {ref}** — {ACCEPTED_MISMATCHES[ref]}")

    lines += [
        "",
        "## Corrections applied to Crossref metadata",
        "",
        "Crossref is authoritative for identity but not always for presentation. Three classes",
        "of correction were applied, each recorded in `OVERRIDES` in the build script so the",
        "seed stays reproducible: depositor errors (all-capital author names from the Nature",
        "1961 and Elsevier 1980 deposits; the ACL deposit for Sentence-BERT gives 3980–3990",
        "where the ACL Anthology and the manuscript both give 3982–3992), book records carrying",
        "only a main title, and article-number journals for which Crossref deposits no page",
        "field at all — those numbers come from the manuscript's printed entries.",
        "",
        "| Printed | Fields corrected |",
        "|---|---|",
    ]
    for ref in sorted(OVERRIDES, key=lambda r: (int(re.match(r"\d+", r).group()), r)):
        lines.append(f"| {ref} | " + ", ".join(f"`{f}`" for f in OVERRIDES[ref]) + " |")
    lines += [
        "",
        "One disagreement was left standing rather than reconciled: printed 42 (DReAMy) gives",
        "pages 406–407 while Crossref gives S406–S407, the supplement pagination for that",
        "*Sleep Medicine* abstract. The seed keeps Crossref's form.",
    ]
    lines += [
        "",
        "## Dropped",
        "",
    ]
    for ref, why in DROPPED.items():
        lines.append(f"- **Printed {ref}** — {why}")
    lines += [
        "",
        "## Hand-written entries",
        "",
        "These have no DOI for the edition the manuscript cites. Where a plausible DOI exists",
        "for a *different* edition or for a review of the work, it was deliberately not",
        "adopted; the reason is recorded so the decision can be revisited rather than",
        "rediscovered.",
        "",
    ]
    for man in MANUAL:
        lines.append(f"- **Printed {man['ref']}** — `{man['key']}` — {man['title']}  ")
        lines.append(f"  {man['flag']}")
    lines += [
        "",
        "## Commentary that could not survive into CSL (migrated 2026-08-24)",
        "",
        "Several printed entries carried interpretive notes that a reference manager has no field",
        "for. They are now in the body text, where regenerating the list cannot lose them:",
        "",
        "- **Printed 32** (Koulack & Goodenough) distinguished the arousal-retrieval account of",
        "  *recall* from the stronger claim that emotionally intense content promotes awakening —",
        "  a hypothesis the paper tests rather than assumes. That distinction is now a sentence in",
        "  Section 3.3, at the ending-audit result.",
        "- **Printed 38** carried the objection that a multilevel autoregressive parameter can",
        "  absorb between-subject mean differences. Section 3.5 now states the objection in prose",
        "  and cites Bos & De Jonge for it, so the second work in that bundle reads as a critique",
        "  rather than as corroboration.",
        "- **Printed 25 and 26** named the model checkpoints the citations license. Both",
        "  checkpoints are already named in Section 2.2, so the notes are redundant in the body",
        "  and survive in the `note` field for a reader of the .bib.",
        "",
        "## How the manuscript now builds",
        "",
        "The manuscript cites by key and pandoc generates the list, so reference numbers follow",
        "order of first appearance by construction and the six bundled entries are just two keys",
        "in one marker. Build the submission copy with:",
        "",
        "```",
        "python3 scripts/build_manuscript.py",
        "```",
        "",
        "That passes `--bibliography` and `--csl` explicitly and applies the Word styling fixes.",
        "The manuscript deliberately does *not* declare those two paths in its YAML: the Obsidian",
        "reference-list plugin resolves a frontmatter `bibliography` against the vault root rather",
        "than the note and throws when it does not resolve, which silently empties its sidebar.",
        "",
        "`nature-brackets.csl` is vendored beside the manuscript (CC BY-SA 3.0) so the build does",
        "not depend on a Zotero install. Swap it for `scientific-reports.csl` or the target",
        "journal's style; nothing else changes.",
        "",
        "## If you route this through Zotero",
        "",
        "Optional — the build above does not need it. But if you want Zotero as the editing",
        "surface, one setting is load-bearing:",
        "",
        "1. Import `references-seed.bib` into Zotero (File → Import).",
        "2. **Pin the imported citation keys.** The keys in this seed are the ones the manuscript",
        "   cites. If Better BibTeX regenerates them from its own formula, every `[@key]` marker",
        "   in the manuscript breaks at once. Import with keys pinned, or reconcile afterwards.",
        "3. Keep the sync one-way. `scripts/zotero_sync.py` pushes this seed into Zotero and never",
        "   reads back, so the DOI verification and brace protection above stay authoritative",
        "   (ADR-0002); an auto-export in the other direction would overwrite both.",
        "4. Spot-check the seven hand-written entries and the ACL/ELRA/NeurIPS proceedings",
        "   records, which are the only places metadata was not machine-verified end to end.",
        "",
    ]
    REPORT_OUT.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
